{"name": "Successfully fill out a text form", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=52433): Max retries exceeded with url: /session/3255df78-5641-4789-92df-8e318dd24af2/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A01122D420>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "trace": "  File \"C:\\Users\\diego\\AppData\\Roaming\\Python\\Python310\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\diego\\AppData\\Roaming\\Python\\Python310\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\text_box_steps.py\", line 8, in step_open_demoqa\n    assert textbox_pages.open_web_page(url)\n  File \"Q:\\demosqa\\pages\\text_box_pages.py\", line 17, in open_web_page\n    self.driver.save_screenshot('../screenshots/open_web_page_error.png')\n  File \"C:\\Users\\diego\\AppData\\Roaming\\Python\\Python310\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 916, in save_screenshot\n    return self.get_screenshot_as_file(filename)\n  File \"C:\\Users\\diego\\AppData\\Roaming\\Python\\Python310\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 892, in get_screenshot_as_file\n    png = self.get_screenshot_as_png()\n  File \"C:\\Users\\diego\\AppData\\Roaming\\Python\\Python310\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 926, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n  File \"C:\\Users\\diego\\AppData\\Roaming\\Python\\Python310\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 937, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n  File \"C:\\Users\\diego\\AppData\\Roaming\\Python\\Python310\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 438, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"C:\\Users\\diego\\AppData\\Roaming\\Python\\Python310\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 290, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"C:\\Users\\diego\\AppData\\Roaming\\Python\\Python310\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 311, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n  File \"C:\\Users\\diego\\AppData\\Roaming\\Python\\Python310\\site-packages\\urllib3\\request.py\", line 74, in request\n    return self.request_encode_url(\n  File \"C:\\Users\\diego\\AppData\\Roaming\\Python\\Python310\\site-packages\\urllib3\\request.py\", line 96, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n  File \"C:\\Users\\diego\\AppData\\Roaming\\Python\\Python310\\site-packages\\urllib3\\poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"C:\\Users\\diego\\AppData\\Roaming\\Python\\Python310\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"C:\\Users\\diego\\AppData\\Roaming\\Python\\Python310\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"C:\\Users\\diego\\AppData\\Roaming\\Python\\Python310\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"C:\\Users\\diego\\AppData\\Roaming\\Python\\Python310\\site-packages\\urllib3\\connectionpool.py\", line 787, in urlopen\n    retries = retries.increment(\n  File \"C:\\Users\\diego\\AppData\\Roaming\\Python\\Python310\\site-packages\\urllib3\\util\\retry.py\", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "steps": [{"name": "Given I am on the \"https://demoqa.com/text-box\" page", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=52433): Max retries exceeded with url: /session/3255df78-5641-4789-92df-8e318dd24af2/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A01122D420>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "trace": "  File \"C:\\Users\\diego\\AppData\\Roaming\\Python\\Python310\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\diego\\AppData\\Roaming\\Python\\Python310\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\text_box_steps.py\", line 8, in step_open_demoqa\n    assert textbox_pages.open_web_page(url)\n  File \"Q:\\demosqa\\pages\\text_box_pages.py\", line 17, in open_web_page\n    self.driver.save_screenshot('../screenshots/open_web_page_error.png')\n  File \"C:\\Users\\diego\\AppData\\Roaming\\Python\\Python310\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 916, in save_screenshot\n    return self.get_screenshot_as_file(filename)\n  File \"C:\\Users\\diego\\AppData\\Roaming\\Python\\Python310\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 892, in get_screenshot_as_file\n    png = self.get_screenshot_as_png()\n  File \"C:\\Users\\diego\\AppData\\Roaming\\Python\\Python310\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 926, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n  File \"C:\\Users\\diego\\AppData\\Roaming\\Python\\Python310\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 937, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n  File \"C:\\Users\\diego\\AppData\\Roaming\\Python\\Python310\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 438, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"C:\\Users\\diego\\AppData\\Roaming\\Python\\Python310\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 290, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"C:\\Users\\diego\\AppData\\Roaming\\Python\\Python310\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 311, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n  File \"C:\\Users\\diego\\AppData\\Roaming\\Python\\Python310\\site-packages\\urllib3\\request.py\", line 74, in request\n    return self.request_encode_url(\n  File \"C:\\Users\\diego\\AppData\\Roaming\\Python\\Python310\\site-packages\\urllib3\\request.py\", line 96, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n  File \"C:\\Users\\diego\\AppData\\Roaming\\Python\\Python310\\site-packages\\urllib3\\poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"C:\\Users\\diego\\AppData\\Roaming\\Python\\Python310\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"C:\\Users\\diego\\AppData\\Roaming\\Python\\Python310\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"C:\\Users\\diego\\AppData\\Roaming\\Python\\Python310\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"C:\\Users\\diego\\AppData\\Roaming\\Python\\Python310\\site-packages\\urllib3\\connectionpool.py\", line 787, in urlopen\n    retries = retries.increment(\n  File \"C:\\Users\\diego\\AppData\\Roaming\\Python\\Python310\\site-packages\\urllib3\\util\\retry.py\", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "start": 1688739590323, "stop": 1688739622720}, {"name": "When I enter \"John Smith\" in the \"Full Name\" field", "status": "skipped", "start": 1688739622723, "stop": 1688739622723}, {"name": "And I enter \"johnSmith@example.com\" in the \"Email\" field", "status": "skipped", "start": 1688739622723, "stop": 1688739622723}, {"name": "And I enter \"Calle 71 bis No. 91-67\" in the \"Current Address\" field", "status": "skipped", "start": 1688739622723, "stop": 1688739622723}, {"name": "And I enter \"Carrera 120a 77b 82\" in the \"Permanent Address\" field", "status": "skipped", "start": 1688739622723, "stop": 1688739622723}, {"name": "When I click the \"Submit\" button", "status": "skipped", "start": 1688739622723, "stop": 1688739622723}, {"name": "Then I see the information at the bottom of the form", "status": "skipped", "start": 1688739622723, "stop": 1688739622723}], "start": 1688739590321, "stop": 1688739622723, "uuid": "429f9cf5-42e5-45d7-8973-09c20ece76ba", "historyId": "c181cbfe6d90fc194b5e2412e3aa45b6", "fullName": "TextBox: Successfully fill out a text form", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "TextBox"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}